### ISSUE TITLE
增加类似chrome的proxy-bypass-list功能

### ISSUE THREAD

**Issue by musicyin** [456vv/vsocks5#2]
情景是电商环境
代理服务器是按流量计算的，想某些域名不走代理，直连
但用了几家指纹浏览器不支持proxy-bypass-list功能
想从代理转发下手

如果可以有打赏功能就好，免费的要求那么多不好

作者有没有编写有关指纹浏览器的作品
我的需求是每次启动浏览器指纹随机，并再固定指纹就够了，再配合go-rod进行自动化
canvas指纹，audio指纹，font指纹，webgl 指纹，每页随机是会搞（透过js）
但是遇到特定的网页，就得从头到尾固定指纹能过

**Comment by 456vv** [comment]
go-rod 是可以在请求前指定代理的，也可以在页面加载前注入js，改变指纹；你可以先了解：privoxy,Charles,Proxifier,brave-portable。

电商环境作用已经不大了，不管是开店群或采集。搞来搞去都是在浪费时间。如果只是为了减少重复操作，可以使用浏览器插件操作。
